### ISSUE TITLE
Loader for custom blocks

### ISSUE THREAD

**Issue by jonasrdm** [ktsn/vue-route-generator#11]
Hi!

When I try to add the `<route-meta>` to a page i get the following error:

```
Module parse failed: Unexpected token (3:22)
You may need an appropriate loader to handle this file type.
|
| {
>   "requerAutenticacao": true
| }
|
```

It looks like we have to implement a loader for this custom tag. 

So, I'd like to make a suggestion: why not add the "how-to" on the docs under metadata? Maybe offer a default implementation inside the library as an option.

**Comment by ktsn** [comment]
Thanks for filing issue. This is actually vue-loader's bug and I already reported (https://github.com/vuejs/vue-loader/issues/1394, https://github.com/ktsn/vue-cli-plugin-auto-routing/issues/4). I thought to fix it by myself but I couldn't because I really busy recently...

**Comment by tomieric** [comment]
In my project, create new file `meta-loader.js`
```
module.exports = function (source, map) {
  this.callback(
    null,
    `export default function (Component) {
      Component.options._meta = ${
        JSON.stringify(source)
      }
    }`,
    map
  )
}
```

In your webpack.config.js, add like this:

```
...
module: {
      rules: [
        {
          resourceQuery: /blockType=route-meta/,
          loader: require.resolve('./meta-loader.js')
        }
     ]
}
...
```

In my project to cmmand `yarn dev`, Oh yeah! It's look like Ok

[https://vue-loader.vuejs.org/guide/custom-blocks.html#example](https://vue-loader.vuejs.org/guide/custom-blocks.html#example)

I'm created a webpack plugin to use `vue-route-generator`, bucase want to support mutil-pages, The project `vue-cli-plugin-auto-routing` didn't.

**Comment by ktsn** [comment]
This should be fixed in vue-loader v15.6.3.

**Comment by mjones2620** [comment]
@tomieric Hey, when I tried this, I get an error about relative modules not found. How did you fix?

**Comment by ThaDaVos** [comment]
Sorry for dropping in here but I'm still having this issue when using vue-loader v15.9.0
I'm using Laravel-Mix (maybe that's doing something) but I keep seeing the issue about the additional loader, I even added my own custom loader but the error is still there...

**Comment by ThaDaVos** [comment]
My Loader:
```JavaScript
module.exports = function (source, map) {
    this.callback(
      null,
      `export default function (Component) {
        Component.options.__meta = ${
          JSON.stringify(source)
        }
      }`,
      map
    )
  }
```
My webpack.mix.js
```JavaScript
const mix = require('laravel-mix');
const path = require('path');
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
const VueAutoRoutingPlugin = require('vue-auto-routing/lib/webpack-plugin');

const APP_URL = new URL(process.env.APP_URL || 'http://localhost');

mix
    .options({
        // extractVueStyles: true,
        hmrOptions: {
            host: APP_URL.host,
            port: 3000
        },
        devServer: {
            allowedHosts: [
                '.local.muntz.nl'
            ],
            public: APP_URL.host
        }
    })
    .webpackConfig({
        plugins: [
            new VuetifyLoaderPlugin(),
            new VueAutoRoutingPlugin({
                pages: path.resolve(__dirname, 'resources/components/pages'),
                importPrefix: '#/pages/'
            }),
        ],
        resolve: {
            alias: {
                '#': path.resolve(__dirname, 'resources/components')
            }
        },
        module: {
            rules: [
                {
                    resourceQuery: /blocktype=route-meta/,
                    loader: require.resolve('./meta-loader.js')
                }
            ]
        }
    })
    .babelConfig({
        plugins: [
            '@babel/plugin-syntax-dynamic-import',
            '@babel/plugin-proposal-optional-chaining'
        ],
    })
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
```

**Comment by ThaDaVos** [comment]
NVM, it's an issue with the vuetify-loader - it's trying to load the block while it shouldn't...
